import { BookOpen, Database, GitBranch, ShieldCheck } from 'lucide-react';
import type { ReactNode } from 'react';

const ADR_LIST = [
  ['ADR-000', 'Staged build process & restart'], ['ADR-001', 'Business problem framing'], ['ADR-002', 'Success metric & prioritisation'], ['ADR-003', 'Reproducible data extraction'], ['ADR-004', 'Data understanding & validation'], ['ADR-005', 'Hypothesis-driven EDA'], ['ADR-006', 'Feature engineering'], ['ADR-007', 'Leakage-safe pipeline'], ['ADR-008', 'Baseline logistic regression'], ['ADR-009', 'Champion XGBoost selection'], ['ADR-010', 'Calibration & conformal prediction'], ['ADR-011', 'Survival analysis'], ['ADR-012', 'Offline Thompson-sampling replay'], ['ADR-013', 'Counterfactual scenario search'], ['ADR-014', 'FastAPI serving architecture'], ['ADR-015', 'Docker, CI/CD & tests'], ['ADR-016', 'SHAP investigation'], ['ADR-017', 'Hardening & split audit'], ['ADR-018', 'Durable storage & lineage scaling'],
];

export function AboutPage() {
  return (
    <main className="mx-auto w-full max-w-6xl space-y-8 p-5 sm:p-8">
      <header className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-700">System design</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">A decision documented from business constraint to serving artifact.</h1><p className="mt-3 text-sm leading-6 text-slate-600">RetentionAI is a portfolio system for a constrained business question: which customers should a telecom retention team prioritise when it has a finite call budget?</p></header>

      <section className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-300">System path</p><div className="mt-5 grid gap-3 md:grid-cols-6">{['Telco snapshot', 'Train-only features', 'XGBoost', 'Calibration + uncertainty', 'Versioned artifact', 'Decision-support UI'].map((item, index) => <div key={item} className="flex items-center gap-3 md:block"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white/10 text-xs font-semibold text-indigo-200">{index + 1}</span><p className="text-sm font-medium md:mt-3">{item}</p></div>)}</div><p className="mt-6 max-w-3xl text-sm leading-6 text-slate-300">Telco snapshot → leakage-safe features → XGBoost → calibration + uncertainty → versioned artifact → API → decision-support dashboard.</p></section>

      <section className="grid gap-4 md:grid-cols-2"><Proof icon={<GitBranch className="h-5 w-5" />} title="Train-only feature fitting" text="Encoders, filters, and transformers are fit on training data so evaluation and live scoring do not inherit target leakage." /><Proof icon={<ShieldCheck className="h-5 w-5" />} title="Interpretable probability and uncertainty" text="Calibration supports meaningful thresholding; conformal prediction signals when a case remains ambiguous." /><Proof icon={<Database className="h-5 w-5" />} title="Versioned, verified artifacts" text="Serving artifacts record integrity metadata and data provenance rather than silently rebuilding on startup." /><Proof icon={<BookOpen className="h-5 w-5" />} title="Auditable implementation choices" text="The ADRs record alternatives, trade-offs, discovered limitations, and the reasoning behind the final design." /></section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Dataset and scope</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Fact label="Dataset" value="Kaggle Telco Customer Churn" note="7,043 rows, 21 attributes" /><Fact label="What is estimated" value="Churn propensity" note="A ranking input for a limited review budget" /><Fact label="What is not established" value="Offer uplift" note="No randomised retention-outcome data" /></div><p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900"><strong>Important limitation:</strong> a propensity score does not prove that an offer will retain the customer. The counterfactual view is a limited model-consistent scenario, not a causal recommendation.</p></section>

      <details className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><summary className="cursor-pointer text-sm font-semibold text-slate-950">Read architecture decisions ({ADR_LIST.length})</summary><div className="mt-5 grid gap-2 sm:grid-cols-2">{ADR_LIST.map(([id, title]) => <div key={id} className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700"><span className="mr-2 font-mono text-xs font-bold text-indigo-700">{id}</span>{title}</div>)}</div></details>
    </main>
  );
}

function Proof({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="inline-flex rounded-lg bg-indigo-50 p-2 text-indigo-700">{icon}</span><h2 className="mt-4 text-base font-semibold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
function Fact({ label, value, note }: { label: string; value: string; note: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold text-slate-950">{value}</p><p className="mt-1 text-xs leading-5 text-slate-500">{note}</p></div>; }
